name: O-health Nightly

on:
  push:
    branches:
      - build
  workflow_dispatch:

jobs:

  build_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          cache: true
          
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev make python3-pip python3-setuptools patchelf desktop-file-utils libgdk-pixbuf2.0-dev fakeroot strace fuse

      - run: |
          flutter pub get
          flutter build apk

      - name: rename
        if: ${{ github.event_name != 'release' }}
        run: mv build/app/outputs/apk/release/app-* build/app/outputs/apk/release/o-health-android-nightly.apk
      - uses: svenstaro/upload-release-action@latest
        with:
       
          file: build/app/outputs/apk/release/o-health-*
          file_glob: true
          prerelease: ${{ github.event_name != 'release' }}
          release_name: ${{ github.event_name == 'release' && github.event.release.name || 'Development Build' }}
          tag: ${{ github.event_name == 'release' && github.event.release.tag_name || 'nightly' }}
          overwrite: true
